### ISSUE TITLE
Crashing on doing pretty much anything

### ISSUE THREAD

**Issue by Omen267901** [taedixon/boosters-lab#10]
I'm getting a crash in BL upon doing literally anything other than just opening the program. Changing tileset scale, pressing New or Open, anything. For reference last I used BL (late 2016) it worked fine.

Version: 0.5 (happened in 0.4.5.5 too)
Java: Most recent 8, both 64 and 32.
OS: Windows 10

 Java log: https://pastebin.com/Th4CQskZ

**Comment by taedixon** [comment]
Interesting crash, although as far as I can tell this seems to be more of a system/configuration issue than a problem with BL specifically.

Are you using an unusual Windows Theme? Do other Java programs have a similar issue?

If you're able to build the project yourself, try commenting out the block at https://github.com/taedixon/boosters-lab/blob/master/src/ca/noxid/lab/EditorApp.java#L464 where the application tries to use the system Look & Feel. There's a very similar crash report at https://bugs.openjdk.java.net/browse/JDK-8170517 where they reported they were able to workaround the issue by not setting the Look & Feel.

**Comment by Omen267901** [comment]
I'll try building it myself, got a guide on that? 

Also, AFAIK I'm not using an unusual theme, but I don't know how to check. 

Haven't launched any Java programs in a while. Will minecraft work for a test? I don't know if I have anything else.

**Comment by taedixon** [comment]
The easiest way is to install IntelliJ and open the project's .iml file. It's not set up for easy command-line compilation right now.

Minecraft might work, you can also try this
[TscEditor_lftest.zip](https://github.com/taedixon/boosters-lab/files/1002172/TscEditor_lftest.zip)
I've included two versions of an old program, one with Java Look & Feel and one with the system's. If one works and not the other, then that's the problem. If both don't work, it's your system's problem. If both DO work, it's something weird with BL.

**Comment by Omen267901** [comment]
The look & Feel one crashed. I'll try your suggestion.

**Comment by Omen267901** [comment]
I'm totally lost. Where do I get the .imi file and how do I open it in IntelliJ?

**Comment by taedixon** [comment]
Uh.. `Booster's Lab.iml` is part of the project root directory. You should be able to import the project with the option that's like `import` or `open`.

 I can add an option to disable the Look & Feel but it may be a little while before I post another release.

**Comment by Omen267901** [comment]
http://i.imgur.com/vPL0a7G.png

I think im confused on what the project is.

**Comment by taedixon** [comment]
https://github.com/taedixon/boosters-lab bud
clone or download the repository for the source

**Comment by Omen267901** [comment]
I could have sworn that's what I did, oops

**Comment by taedixon** [comment]
the release will always be equal to or behind master
I haven't really got the availability to guide you through this process so if it proves to be a challenge you can just wait for me to find the time to implement the fix myself.

**Comment by Omen267901** [comment]
Ok. I'll just wait for a fix. Thanks for your time.

As a side note, I assume this will be changeable in a file? I don't think I'd be able to change it in the program itself. (probably a dumb question)

**Comment by taedixon** [comment]
it'll be some kind of external setting.

**Comment by Omen267901** [comment]
Thanks. Suppose I'll close this now.
