### ISSUE TITLE
[Suggestion] Adding "place entity" to the right-click menu.

### ISSUE THREAD

**Issue by Enlight1** [taedixon/boosters-lab#19]
One of the most common questions regarding using BL for the first time is figuring out how to place entities. Not gonna argue about the "i" key, since it is already known to be necessary to fix/overcome other issues.

One suggestion I have is to add a "place entity" option to the right-click menu when it entity mode. This option could/should be labeled "Place Entity (i)" so that the new user can both find it and determine the shortcut for it just from clicking around while learning the editor.

**Comment by taedixon** [comment]
yeah, this sounds like a reasonable compromise tbh

**Comment by taedixon** [comment]
Resolved in 7242eaf
