### ISSUE TITLE
I would like to contribute a new hack XML file.

### ISSUE THREAD

**Issue by nlburgin** [taedixon/boosters-lab#24]
[curlys_nemesis.xml.zip](https://github.com/taedixon/boosters-lab/files/2923245/curlys_nemesis.xml.zip)

So, I wanted to do a challenge run where you complete the good ending with the mimiga mask on and no Booster, using the machine gun to fly, but it turned out that was impossible in the stock game. 

I could have just used a couple hacked saves to play through Last Cave (hidden) and Sacred Grounds like that anyway, but I decided to go a step further and download Booster's lab to try and make it possible to do properly. I figured out how to do script edits and ended up making a complete mod (that I may try and actually release to the public later) where you never collect anything but the machine gun and Momorin doesn't give you back your Booster after finishing the rocket.

I could have left it at that, but... after going to all that trouble to make a machine gun only run, it seemed disappointing that Curly ruined it by having a Nemesis. I could have just edited her out of the script completely, but that seemed unsatisfactory. So after some serious reverse engineering I never expected to get into at the start of this whole thing (which was only possible thanks to the CSE2 decompilation project), I ended up making a new hack, which is attached as a zipped XML file, and listed below:

````
<?xml version="1.0" encoding="UTF-8"?>
<hack name="Curly's Nemesis Hack">
	<panel>
		<field type="label">
			Bullet Type ID (can mimic other weapons)
		</field>
		<field type="text" offset="0x46762e" size="1"/>
		
		<field  type="label">
			Bullet Type ID to use for onscreen limit test
		</field>
		<field type="text" offset="0x4675f4" size="1"/>
		
		<field type="label">
			Number of Bullets Allowed Onscreen
		</field>
		<field type="text" offset="0x4675ff" size="1"/>
		    
		<field type="label" col = "1">
			ID of Sound Effect to play
		</field>
		<field type="text" offset="0x467660" size="1"/>
		
		<field type="label">
			Automatic Fire (1 shot per frame, kinda broken)
		</field>

		<field type="check" name="Autofire (Try with L1 Polar Star bullet for reasonable results)">
            <checked>
                <field type="data" offset="0x467603">
                    10 E2 49 00
                </field>
            </checked>
            <unchecked>
                <field type="data" offset="0x467603">
                    14 E2 49 00
                </field>
            </unchecked>
        </field>
    </panel>
</hack>
````
![screenshot_2019-03-03_10-26-42](https://user-images.githubusercontent.com/30382228/53697465-57952f80-3d9f-11e9-8918-4b061f7bf940.png)

It allows you to change the bullet type spawned by Curly's Nemesis, set the maximum of those bullets onscreen, and optionally set it to rapid-fire instead of fire once per trigger pull.

The rapid fire is one shot per frame, which is usually insane, but works well with Lv1 polar star bullets (set bullet id number to 4) and the max on-screen shots set to a high number like 50. Combine that with the existing weapon hack to increase Lv1 polar star bullet lifetime from 8 to 18 frames (increasing range), and some edits to NpcSym.bmp, and Curly is now wielding a reasonable "machine gun".

![mpv-shot0021](https://user-images.githubusercontent.com/30382228/53697291-308a2e00-3d9e-11e9-84bb-31a674dddcad.jpg)

Anyway, I'm actually pretty proud of my Curly's Nemesis hack-xml file and am wondering if you would like to carry it upstream and bundle it along with the others in the next release of Booster's Lab.

**Comment by taedixon** [comment]
The normal process for this is to create a Pull Request but it seems fine so, I've included it in 0.5.1.1 under "misc patches"
