### ISSUE TITLE
Booster's lab 0.5.1.0 displays wrong version internally

### ISSUE THREAD

**Issue by nlburgin** [taedixon/boosters-lab#25]
![Screenshot_2019-03-10_20-09-27](https://user-images.githubusercontent.com/30382228/54093649-6e73ed00-4370-11e9-88da-abce85954dab.png)

For a second I thought I had opened the old version by mistake. But I double checked, and that was not the case. I'm using 0.5.1.0 (NO_JRE), but the title bar and the "about" dialog seem to be unaware that any such update has occurred.

**Comment by taedixon** [comment]
Fixed in 0.5.1.1
