### ISSUE TITLE
Add npc.tbl entry

### ISSUE THREAD

**Issue by GDB-spur** [taedixon/boosters-lab#30]
Is add entity finished? I'm having trouble using it.

**Comment by Leo40Git** [comment]
press I

**Comment by GDB-spur** [comment]
Oh, I meant adding completely new entities scripted in ASM. I have made an entity 361 and there is an add new entity button that doesn't seem to add it.

**Comment by GDB-spur** [comment]
Is that possibly an upcoming feature?

**Comment by GDB-spur** [comment]
If there is something that I can do to help finalize this feature, please let me know. I'm talking about the feature that says add in entity 361 to the game. I have increased the array limit but I need to add in more entities. Could boosters lab be able to do this in the near future? I can help in any way I can.

**Comment by Leo40Git** [comment]
Sorry for not responding, I went to sleep.
I'll look into that later today.

**Comment by GDB-spur** [comment]
Oh? Awesome! Let me know if I can help :)

**Comment by Leo40Git** [comment]
Sorry for taking so long!
Booster's Lab already has this feature. Switch to the "Entity" view (under "Tile"), click on "Edit npc.tbl" and then click on "Add New".
After you add your new entity, click on "Save & Close".

**Comment by GDB-spur** [comment]
I was wondering if you specify an ASM address within it so it knows where to go

**Comment by Leo40Git** [comment]
That's something you need ASM editing for, a feature that isn't (and will likely never) be included in Booster's Lab.

**Comment by GDB-spur** [comment]
Ohhh ok. Thank you :)
